name: Code Quality

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==7.0.0 \
        flake8-broken-line==1.0.0 \
        flake8-isort==6.1.1 \
        flake8-plugin-utils==1.3.3 \
        flake8-return==1.2.0 \
        isort==5.13.2 \
    - name: Run Flake8
      run: |
        python flake8
